---
title: "Variant forecasting using EpiNow2"
output: 
  html_notebook:
    code_folding: hide
---

```{r}
library(here)
library(tidyverse)
library(covidregionaldata)
library(EpiEstim)
library(EpiNow2)
library(patchwork)
library(httr)
library(jsonlite)

source(here("code/colours", "KTD_colours.R"))
```

```{r}
## download case data through opencovid.ca API
res <- GET("https://api.opencovid.ca/timeseries", query = list(
  stat = "all", geo = "can", before = "2023-04-23", fmt = "json"
))

json_data <- fromJSON(rawToChar(res$content))
dat <- bind_rows(data$data)
case_data <- dat %>%
  filter(name == "cases")

## load variant data downloaded from CoV-Spectrum
#voc_data <- read_csv(here("data", "VariantTimeDistributionPlot.xbb.1.9.1.csv"))
voc_data <- read_csv(here("data", "VariantTimeDistributionPlot.xbb1.5.csv"))

## create week variable
voc_data <- voc_data %>%
  mutate(
    date = as.Date(date),
    week = lubridate::floor_date(date, unit = "week", week_start = 1),
    epiweek = lubridate::epiweek(date),
    smooth_prop = predict(loess(proportion ~ as.numeric(date), span = 0.1, data=.),
                          data.frame(date = seq(min(as.numeric(date)), max(as.numeric(date)), 1))),
    smooth_prop_lo = predict(loess(proportionCILow ~ as.numeric(date), span = 0.1, data=.),
                          data.frame(date = seq(min(as.numeric(date)), max(as.numeric(date)), 1))),
    smooth_prop_hi = predict(loess(proportionCIHigh ~ as.numeric(date), span = 0.1, data=.),
                          data.frame(date = seq(min(as.numeric(date)), max(as.numeric(date)), 1))),
  )

## create 7-day rolling average for case series, and case series lagged by 3 and 7 days (to account for reporting delays)
case_data <- case_data %>%
  mutate(
    date = as.Date(date),
    week = lubridate::floor_date(date, unit = "week", week_start = 1),
    epiweek = lubridate::epiweek(date),
    cases_ma7 = zoo::rollmean(value_daily, k = 7, align = "right", fill = NA), # 7-day moving average
    cases_ma7_lag3 = lead(cases_ma7, 3),
    cases_ma7_lag7 = lead(cases_ma7, 7)
  )

## merge case and variant data from date of first detection
min_date <- voc_data %>%
  filter(proportion > 0) %>%
  summarise(min(date)) %>%
  pull()

dat2 <- left_join(
  voc_data %>% select(date, contains("prop")), 
  case_data %>% select(date, "cases" = value_daily, "cases_smooth" = cases_ma7, 
                       "cases_smooth_lag3" =  cases_ma7_lag3, "cases_smooth_lag7" = cases_ma7_lag7),
  by = "date"
  ) %>% 
  filter(date >= min_date) %>%
  mutate(
    voc_cases = round(cases_smooth * smooth_prop),
    voc_cases_lo = cases_smooth * smooth_prop_lo,
    voc_cases_hi = cases_smooth * smooth_prop_hi,
    voc_cases_lag3 = round(cases_smooth_lag3 * smooth_prop),
    voc_cases_lag7 = round(cases_smooth_lag7 * smooth_prop)
  )
```

```{r}
## plot case and variant data
dat <- bind_rows(
  case_data %>% select(date, "value" = value_daily, cases_ma7, cases_ma7_lag3, cases_ma7_lag7) %>% mutate(type = "cases"),
  voc_data %>% select(date, "value" = proportion, "prop_lo" = proportionCILow, "prop_hi" = proportionCIHigh, smooth_prop) %>% mutate(type = "sequences")
)

dat %>%
  filter(date >= as.Date("2023-03-01")) %>%
  ggplot() + 
  geom_line(aes(x = date, y = value)) +
  geom_line(aes(x = date, y = cases_ma7), col = my_red) +
  geom_line(aes(x = date, y = smooth_prop), col = my_red) +
  geom_ribbon(aes(x = date, ymin = prop_lo, ymax = prop_hi), alpha = 0.5) +
  facet_wrap(~type, nrow = 2, scales = "free_y")
  
```

```{r}
## plot overall vs estimated variant cases
dat2 %>%
  ggplot() +
  geom_area(aes(x = date, y = cases_smooth), fill = "gray50", alpha = 0.5) +
  geom_area(aes(x = date, y = voc_cases), fill = my_red, alpha = 0.5) +
  scale_x_date(date_labels = "%d-%b-%y", date_breaks = "1 month") +
  labs(
    y = "Estimated cases",
    x = ""
  )

ggsave(here("plots", "voc_dailycaseestimates_example.png"), device = "png", width = 12, height = 12, dpi = 300)
```
```{r}
## estimate Re(t) using parametric method

## define mean and SD for serial interval distribution (Gamma distribution)
#si_mean <- 5.2  # values from Leung et al., Nat Commun 2021; 12: 1501. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7940469/
#si_sd <- 0.33

si_mean <- 3.3 # values from https://www.medrxiv.org/content/10.1101/2022.01.08.22268920v1.full.pdf
si_sd <- 3.5

#variant <- "XBB.1.16"

## create variant cases dataframes for extimation

# original
incid <- dat2 %>%
  select("I" = voc_cases, "dates" = date)

# with 3-day reporting delay
incid3 <- dat2 %>%
  select("I" = voc_cases_lag3, "dates" = date)

# with 7-day reporting delay
incid7 <- dat2 %>%
  select("I" = voc_cases_lag7, "dates" = date) %>%
  filter(!is.na(I))

## Re(t) estimation
res_parametric_si <- estimate_R(incid, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = si_mean, 
                                  std_si = si_sd))
)

res_parametric_si3 <- estimate_R(incid3, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = si_mean, 
                                  std_si = si_sd))
)

res_parametric_si7 <- estimate_R(incid7, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = si_mean, 
                                  std_si = si_sd))
)
```

```{r}
## align epidemic curve and Re(t) estimates for plotting
d <- incid %>%
  mutate(
    day = row_number()
  ) %>%
  left_join(
    res_parametric_si$R, by = c("day" = "t_end")
  )

d3 <- incid3 %>%
  mutate(
    day = row_number()
  ) %>%
  left_join(
    res_parametric_si3$R, by = c("day" = "t_end")
  )

d7 <- incid7 %>%
  mutate(
    day = row_number()
  ) %>%
  left_join(
    res_parametric_si7$R, by = c("day" = "t_end")
  )
```

```{r, fig.height = 9, fig.width=16}
## convert to long format for faceting and add threshold line at Re(t) = 1
d2 <- bind_rows(
  d %>% select(day, "date" = dates, "value" = I) %>% mutate(type = "incidence", delay = "No delay"),
  d %>% select(day, "date" = dates, "value" = `Median(R)`, starts_with("Quantile")) %>% mutate(type = "Re(t)", delay = "No delay"),
  d3 %>% select(day, "date" = dates, "value" = I) %>% mutate(type = "incidence", delay = "3-day delay"),
  d3 %>% select(day, "date" = dates, "value" = `Median(R)`, starts_with("Quantile")) %>% mutate(type = "Re(t)", delay = "3-day delay"),
  d7 %>% select(day, "date" = dates, "value" = I) %>% mutate(type = "incidence", delay = "7-day delay"),
  d7 %>% select(day, "date" = dates, "value" = `Median(R)`, starts_with("Quantile")) %>% mutate(type = "Re(t)", delay = "7-day delay")
) %>%
  mutate(
    yintercept = ifelse(type == "incidence", NA_integer_, 1),
    delay = factor(delay, levels = c("No delay", "3-day delay", "7-day delay"))
  ) 

#plot(res_parametric_si)

d2 %>%
  ggplot() +
  geom_ribbon(aes(x = date, ymin = `Quantile.0.025(R)`, ymax = `Quantile.0.975(R)`), fill = "gray80", alpha = 0.5) +
  geom_ribbon(aes(x = date, ymin = `Quantile.0.25(R)`, ymax = `Quantile.0.75(R)`), fill = "gray50", alpha = 0.5) +
  geom_line(aes(x = date, y = value, group = type)) +
  geom_hline(aes(yintercept = yintercept), linetype = "dashed", size = 0.5) +
  facet_grid(type~delay, scales = "free_y") +
  scale_x_date(date_labels = "%d-%b-%y", date_breaks = "2 weeks") +
  labs(
    y = "Re(t) / Daily cases",
    x = "Date"
  )
```
```{r, fig.height=6, fig.width=12}
## plot only no delay scenario
d2 %>%
  filter(delay == "No delay") %>%
  ggplot() +
  geom_ribbon(aes(x = date, ymin = `Quantile.0.025(R)`, ymax = `Quantile.0.975(R)`), fill = "gray80", alpha = 0.5) +
  geom_ribbon(aes(x = date, ymin = `Quantile.0.25(R)`, ymax = `Quantile.0.75(R)`), fill = "gray50", alpha = 0.5) +
  geom_line(aes(x = date, y = value, group = type)) +
  geom_hline(aes(yintercept = yintercept), linetype = "dashed", size = 0.5) +
  facet_wrap(~type, nrow = 2, scales = "free_y") +
  scale_x_date(date_labels = "%d-%b-%y", date_breaks = "2 weeks") +
  labs(
    y = "Re(t) / Daily cases",
    x = "Date"
  )

ggsave(here("plots", "voc_Restimates_example.png"), device = "png", width = 12, height = 12, dpi = 300)
```
```{r}
## short-term forecasts with EpiNow2
# reporting_delay <- list(
#   mean = convert_to_logmean(2, 1), sd = convert_to_logsd(2, 1), max = 10,
#   dist = "lognormal"
# )

# note that fixed = TRUE assumes no variation in mean and SD for intervals
generation_time <- get_generation_time(
  disease = "SARS-CoV-2", source = "ganyani", max = 10, fixed = TRUE
)
incubation_period <- get_incubation_period(
  disease = "SARS-CoV-2", source = "lauer", max = 10, fixed = TRUE
)

## set start date
start_date <- as.Date("2023-03-01")
reported_cases <- incid %>% 
  select("date" = dates, "confirm" = I) %>%
  filter(date >= start_date)

## set seed
set.seed(20230502)

estimates <- epinow(
  reported_cases = reported_cases,
  generation_time = generation_time_opts(generation_time),
  delays = delay_opts(incubation_period), #, reporting_delay),
  rt = rt_opts(prior = list(mean = 1, sd = 0.1)),
  stan = stan_opts(cores = 4, control = list(adapt_delta = 0.99), samples = 4000),
  verbose = interactive()
)

```
```{r}
## diagnostic plots can be obtained as below
#rstan::plot(estimates$estimates$fit, plotfun = "rhat") #rhat
#rstan::plot(estimates$estimates$fit, plotfun = "trace") #trace plots, add pars = c() to specify parameters to plot
```


```{r, fig.height=9, fig.width=12}
## plot summaries
plot(estimates, type = "summary")
```

